name: Upload dotnet package

on:
  release:
    types: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.8.x' # SDK Version to use.
      - run: dotnet build --configuration Release
